### ISSUE TITLE
Problem compiling in Arduino IDE

### ISSUE THREAD

**Issue by FrxnkBv** [Matrixchung/SFM-V1.7#1]
Hello friend, I am something new in the world of programming, I had not found a library for this type of sensor until today.
When trying to compile I get the following error:
![image](https://user-images.githubusercontent.com/117314153/210396920-bfee42fe-95f1-4842-89d0-e7f78edc263d.png)
I hope you can help me, thank you.

**Comment by Matrixchung** [comment]
Hi FrxnkBv,
This project is initially for ESP32-Arduino platform, and I have made some changes to support original Arduino MCUs such as Arduino Uno etc. **from software side**.
**However**, the fingerprint module's working electricity level is 3.3V which is the same as ESP32's, while Arduino's GPIO level is 5V. That means if you connect the module's RX or TX pin directly to the MCU without convert, it may break the module itself and cause severe damage.
So, all in all, I will consider using this module with ESP32 or 3.3v modified Arduino, rather than original 5V Arduino.
Thanks for issue and welcome to provide any further information!
