### ISSUE TITLE
"Touch_and_unlock" doesn't seem to work.

### ISSUE THREAD

**Issue by FrxnkBv** [Matrixchung/SFM-V1.7#2]
Hi, it's me again, thanks for the previous answer.
The "Serial_register" program works correctly, but the "Touch_and_unlock" doesn't seem to execute anything...
I could look for the possible error but I still don't know much about the language :/

**Comment by Matrixchung** [comment]
When you perform "Serial_register", do the ring show correct color changes and the serial return correct message?
If so, then I think the problem may occur in my example... I will take a deep investigation soon.

**Comment by FrxnkBv** [comment]
Yes, "Serial_register" works correctly, it also shows the data in the serial monitor.

**Comment by Matrixchung** [comment]
Could you please let me know what MCU are you using?
That example works great on ESP32-WROOM-DA.

**Comment by ologit** [comment]
hi, my serial register can't be compiled.
is ESP32 is require? can't I use it directly with my Arduino UNO?

**Comment by Matrixchung** [comment]
> hi, my serial register can't be compiled. is ESP32 is require? can't I use it directly with my Arduino UNO?

Please see [readme](https://github.com/Matrixchung/SFM-V1.7/blob/main/readme.md) for using Arduino Uno directly. It is not tested and could probably harm your hardware.
For the compile problem, make sure you are using the 1.0.1 version, which added multi-platform support. 
Submit a new issue if you still encounter with problems. Best wishes!

**Comment by FrxnkBv** [comment]
> Could you please let me know what MCU are you using? That example works great on ESP32-WROOM-DA.

I am using the ESP32WROOM32 with CH340C and compiling on the "DOIT ESP32 DEVKIT V1" board in Arduino IDE
Is it necessary to do something for the sensor to start recognizing the fingerprint?
For example, in "Serial_register" it was necessary to send a letter to the serial monitor for it to start working.

**Comment by Matrixchung** [comment]
> Is it necessary to do something for the sensor to start recognizing the fingerprint?

In fact, the answer is probably no. The message sent to serial is just a 'trigger' that tells the sensor it should register new fingerprint and save it, instead of enabling the whole sensor. In theory, the minute your finger is pressed on the sensor surface, the SFM_IRQ (TOUCH_OUT) pin should rise from low level, thus creating a rising edge interrupt for MCU, which is the background "trigger" for module to start finger recognition.

"Serial_register" example's registration process seems to have nothing to do with interrupt, so to debug I recommend check your module's TOUCH_OUT using a multimeter to see if the level changes, and manually attach a interrupt to it. Maybe your module is broken, or the interrupt fails to execute. Feel free to add more.

**Comment by FrxnkBv** [comment]
You are correct, apparently IRQ does not send any pulse.
Connect the IRQ pin to 3.3v and the sensor started working, it also started sending data to the serial monitor.
![image](https://user-images.githubusercontent.com/117314153/211241499-4b93db98-1806-4f04-863e-11f6867b9dfd.png)

Thank you so much!

**Comment by Matrixchung** [comment]
> You are correct, apparently IRQ does not send any pulse. Connect the IRQ pin to 3.3v and the sensor started working, it also started sending data to the serial monitor. ![image](https://user-images.githubusercontent.com/117314153/211241499-4b93db98-1806-4f04-863e-11f6867b9dfd.png)
> 
> Thank you so much!

Thank you too for addressing issues and helping me to improve. Have fun!
